{
  "hash": "2c732796a4204b67fc87581e9c6635c2",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Fairness-Aware Machine Learning with ![](../img/Rlogo.png){width=60px}\"\nsubtitle: <span style=\"color:#2C3E50\">11.118/11.218 Applied Data Science for Cities</span>\ndate: \"Last Updated 2025-11-18\"\nformat: html\neditor: visual\nexecute: \n  warning: false\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(caret)\nlibrary(mlr3fairness)\n```\n:::\n\n\n\n\n# Data and Disputes\n\nToday we will explore the COMPAS (Correctional Offender Management Profiling for Alternative Sanctions) model. It was a popular commercial algorithm used by judges and parole officers for scoring criminal defendant’s likelihood of reoffending (recidivism). [ProPublica](https://www.propublica.org/article/how-we-analyzed-the-compas-recidivism-algorithm) has shown that the algorithm is biased in favor of white defendants, and against black inmates, based on a two-year follow-up study (i.e who actually committed crimes or violent crimes after 2 years). The pattern of mistakes across racial groups in this dataset is notable.\n\nThis dataset is frequently used to study machine learning bias and is now readily available through [`mlr3fairness`](https://search.r-project.org/CRAN/refmans/mlr3fairness/html/compas.html) package.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(\"compas\", package = \"mlr3fairness\")\n```\n:::\n\n\n\n\nIf you check out `?mlr3fairness::compas`, you will see its documentation including variable explanations and data processing notes. The data includes basic demographics (`age`, `race`, `sex`), and a few variables about prior offense history, such as charge degree (`c_charge_degree`: F for Felony, M for Misdemeanor), and `length_of_stay`.\n\nThe `decile_score` column is the COMPAS model's estimated risk of recidivism (1–10). The `score_text` column puts these into text categories: Low (1–4), Medium (5–7), and High (8–10) risk.\n\nThen there is the `two_year_recid` column. This is based on Propublica's follow-up. It's a binary variable indicate whether defendant was actually rearrested (1) and not rearrested (0) within two years.\n\n## Evaluate COMPAS\n\nHow did COMPAS come up with the `decile_score` is not known (a proprietary algorithm), but we can treat these scores as a \"predicted label\", and the `two_year_recid` as the \"actual label\" to evaluate this COMPAS's performance.\n\nTo clarify our analysis, we'll create two new columns. The first, **predicted**, will be \"Yes\" if `decile_score` is greater than 5, and \"No\" if otherwise. The second, **actual**, will be \"Yes\" if `two_year_recid` is 1, and \"No\" if it is 0.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncompas <- compas |>\n  mutate(\n    predicted = case_when(\n      decile_score > 5  ~ \"yes\",\n      decile_score <= 5 ~ \"no\"\n    ),\n    actual = factor(\n      two_year_recid,\n      levels = c(0, 1),\n      labels = c(\"no\", \"yes\")\n    )\n  )\n```\n:::\n\n\n\n\n## **Model Accuracy**\n\nHow well does COMPAS predict reoffending? One way to measure it is by checking the model’s accuracy. Since this is a classification problem with \"Yes\" or \"No\" outcomes, accuracy is defined as the proportion of **correct predictions**: both when the model predicts reoffending and the person does reoffend, and when it predicts no reoffending and the person does not.\n\nIn other words, accuracy tells us how often the model is correct overall.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncorrect_predictions <- compas |>\n  filter(\n    (predicted == \"yes\" & actual == \"yes\") |\n    (predicted == \"no\" & actual == \"no\")\n)\n\naccuracy <- nrow(correct_predictions) / nrow(compas)\naccuracy\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.6642903\n```\n\n\n:::\n:::\n\n\n\n\nIn our case, the accuracy of the COMPAS model is about 0.66, meaning it makes the correct prediction 66% of the time. It's not particularly high, but it's better than random guessing (50%).\n\n## Confusion Matrix\n\nAccuracy doesn’t show in what way a model makes mistakes. It treats a **false positive** (predicting someone will reoffend when they won't) the same as a **false negative** (predicting someone won’t reoffend when they will). In practice, these errors can have very different implications.\n\nConfusion matrix breaks down the types of correct and incorrect predictions:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# True Positive: predicted recidivism, actually recidivated\nTP <- sum(compas$predicted == \"yes\" & compas$actual == \"yes\")  \n\n# True Negative: predicted no recidivism, didn't recidivate\nTN <- sum(compas$predicted == \"no\" & compas$actual == \"no\")  \n\n# False Positive: predicted recidivism, didn't recidivate\nFP <- sum(compas$predicted == \"yes\" & compas$actual == \"no\")  \n\n# False Negative: predicted no recidivism, actually recidivated\nFN <- sum(compas$predicted == \"no\" & compas$actual == \"yes\")  \n\n# Create a matrix manually\nconf_matrix <- matrix(c(TN, FN, FP, TP),\n                      nrow = 2, byrow = TRUE,\n                      dimnames = list(Prediction = c(\"N\", \"P\"),\n                                      Reference = c(\"N\", \"P\")))\nconf_matrix\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          Reference\nPrediction    N    P\n         N 2647 1356\n         P  716 1453\n```\n\n\n:::\n:::\n\n\n\n\nThis matrix reads:\n\n```         \n           Reference (Actual)\nPrediction    no     yes\n         -----------------\n      no  |   TN     FN\n      yes |   FP     TP\n```\n\nA perfect classifier would only have non-zero values on it's main diagonal (TN and TP).\n\nTo put this result in our context, in the \"Actual No\" column, there are (2647+716=3363) people who actually did not reoffend. Among them, 716 were misclassified. In other words, about (716/3363 = 21%) non-reoffenders were flagged as high risk. This is the **False Positive Rate (FPR)**: the proportion of non-reoffenders incorrectly predicted as reoffenders.\n\n## Breaking it down by racial groups\n\nIf we take a closer look and break down the confusion matrix by racial groups, we will see that the model’s errors are not evenly distributed.\n\n[The analysis by Propublica](https://www.propublica.org/article/how-we-analyzed-the-compas-recidivism-algorithm) has this quote:\n\n> \"Black defendants were often predicted to be at a higher risk of recidivism than they actually were. Our analysis found that black defendants who did not recidivate over a two-year period were nearly twice as likely to be misclassified as higher risk compared to their white counterparts\"\n\nThis means the **FPR** (predicting someone will reoffend when they won't) is higher for Black defendants compared to white defendants.\n\nWe'll now reproduce this analysis ourselves.\n\nTo make the process easier and reusable, we'll define a function that generates a confusion matrix for any specified race.\n\n> Note: Writing your own function can be a bit less intuitive, but it works like outlining the entire process using “placeholder” variables. After the process is built, you use the function by providing actual variables as inputs to replace those placeholders.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Define a function to calculate confusion matrix cells by race\nconfusion_by_race <- function(df, race_name) {\n  df_race <- df |> filter(race == race_name)\n  \n  TP <- sum(df_race$predicted == \"yes\" & df_race$actual == \"yes\")\n  TN <- sum(df_race$predicted == \"no\" & df_race$actual == \"no\")\n  FP <- sum(df_race$predicted == \"yes\" & df_race$actual == \"no\")\n  FN <- sum(df_race$predicted == \"no\" & df_race$actual == \"yes\")\n  \n  return(c(TP = TP, TN = TN, FP = FP, FN = FN))\n}\n```\n:::\n\n\n\n\nThen calculate the confusion matrix for Black and White population, separately.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Remove other objects from the workspace to start fresh\nrm(list = setdiff(ls(), c(\"compas\", \"confusion_by_race\")))\n\n# Calculate for Black affenders\nb_vals <- confusion_by_race(compas, \"African-American\")\nb_fpr <- b_vals[\"FP\"]/(b_vals[\"FP\"]+b_vals[\"TN\"])\n\n# Calculate for White affenders\nw_vals <- confusion_by_race(compas, \"Caucasian\")\nw_fpr <- w_vals[\"FP\"]/(w_vals[\"FP\"]+ w_vals[\"TN\"])\n\n# Print our results\nstr_glue(\n  \"FPR: \\n\",\n  \"Black defendants: {round(b_fpr*100)}% \\n\",\n  \"White defendants: {round(w_fpr*100)}%\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nFPR: \nBlack defendants: 31% \nWhite defendants: 14%\n```\n\n\n:::\n:::\n\n\n\n\nThis aligns with the Propublic result. Black defendants who did not recidivate over a two-year period were nearly twice as likely to be misclassified as higher risk than their White counterparts.\n\nPropublica has another quote:\n\n> \"White defendants were often predicted to be less risky than they were. Our analysis found that white defendants who re-offended within the next two years were mistakenly labeled low risk almost twice as often as black re-offenders\"\n\nThis points to another type of model error: **False Negative Rate (FNR)**. It tells us, among all people who actually reoffended (the \"Actual Yes\" column), how many were missed by the model (predicted as No).\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate FNR for Black reaffenders\nb_fnr <- b_vals[\"FN\"]/(b_vals[\"FN\"]+b_vals[\"TP\"]) \n\n# Calculate for White reaffenders\nw_fnr <- w_vals[\"FN\"]/(w_vals[\"FN\"]+ w_vals[\"TP\"])\n\n# Print our results\nstr_glue(\n  \"FNR: \\n\",\n  \"Black defendants: {round(b_fnr*100)}% \\n\",\n  \"White defendants: {round(w_fnr*100)}%\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nFNR: \nBlack defendants: 38% \nWhite defendants: 61%\n```\n\n\n:::\n:::\n\n\n\n\nSimilar to Propublica's result, White defendants are almost twice as likely to be incorrectly classify as low-risk compared to Black defendants.\n\nSuch kind of pattern is generally referred to as **disparate impact**: when a decision-making process seems neutral on the surface but still results in unequal outcomes for certain groups. In this case, the COMPAS model tends to over-predict risk for Black defendants and under-predict for White defendants, leading to unequal results.\n\nDoes this mean the COMPAS model is simply problematic? To explore this further, let's try building our own prediction model and see how it performs.\n\n# Logistic classification model\n\nLogistic regression is a supervised learning method that uses a linear combination of variables to predict the probability of a “yes” outcome. When you turn those probabilities into actual labels like “yes” or “no,” it becomes a classification model. The model is based on a straight-line equation, so the line separating the two classes is also straight.\n\n## **Variable selection notes**\n\nChoosing which variables to include in a model is a critical challenge in algorithmic decision-making. Steif’s book highlights an important tension around using predictors like `race` and `prior_count`.\n\nIf we include race in a Multiple Linear Regression (MLR), for example, the results table will show the effect of the `race` variable, which might read: “Being race X increases predicted recidivism by 0.2”. This kind of output is problematic. It means the model will consistently add 0.2 for defendants of race X. In other words, it encodes bias into the predictions.\n\nEven if race is not explicitly included as a predictor, variables like `priors_count` can still reflect historical biases in policing that are correlated with race, leading algorithms to make consistently less accurate predictions for certain socioeconomic groups. Predictors like this, such as redlining districts, eviction history, etc., should be used with caution.\n\n## **Model Building**\n\nWe’ll now repeat the modeling workflow you’ve used in previous sessions.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodeldata <- compas |> \n  select(actual, age, sex, race, c_charge_degree, priors_count, length_of_stay)\n\nset.seed(24)\ntrain_index <- createDataPartition(\n  y = modeldata$actual,\n  p = 0.7,\n  list = FALSE\n)\n\ntrain_data <- modeldata[train_index, ]\ntest_data  <- modeldata[-train_index, ]\n```\n:::\n\n\n\n\nIn the `train()` function, set `method = \"glm\"` to specify that we’re using a generalized linear model. `family = \"binomial\"` indicates that the outcome variable is binary.\n\n> Note: Model comparison tests (such as ANOVA and AIC) will show that `priors_count` significantly improves model performance. So given our available predictors, we will include `priors_count` in our model, while excluding `race`.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlogit_model <- train(\n  actual ~ . - race,  # The \"-\" sign is to remove one specific variable from all (\".\") predictors.\n  data = train_data,\n  method = \"glm\",        \n  family = \"binomial\"\n)\n```\n:::\n\n\n\n\n## **Our Result**\n\nUse our trained logistic classification model to predict class labels for the test set.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npred_class <- predict(logit_model, newdata = test_data)\n\n# take a look at the predicted labels\npred_class |> head(10)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] no  yes yes no  yes no  yes no  no  no \nLevels: no yes\n```\n\n\n:::\n:::\n\n\n\n\nAfter generating these predicted classes, we attach them back to the test set for the subsequent confusion matrix calculation.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# attach the predictions to the test data\ntest_pred <- \n  test_data |> \n  mutate(predicted = pred_class)\n```\n:::\n\n\n\n\nNow reuse our previous function `confusion_by_race` to calculate error metrics by race:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nb_vals <- confusion_by_race(test_pred, \"African-American\")\nb_fpr <- b_vals[\"FP\"] / (b_vals[\"FP\"] + b_vals[\"TN\"])\nb_fnr <- b_vals[\"FN\"] / (b_vals[\"FN\"] + b_vals[\"TP\"])\nb_acc <- (b_vals[\"TP\"] + b_vals[\"TN\"]) / sum(b_vals)\n\nw_vals <- confusion_by_race(test_pred, \"Caucasian\")\nw_fpr <- w_vals[\"FP\"] / (w_vals[\"FP\"] + w_vals[\"TN\"])\nw_fnr <- w_vals[\"FN\"] / (w_vals[\"FN\"] + w_vals[\"TP\"])\nw_acc <- (w_vals[\"TP\"] + w_vals[\"TN\"]) / sum(w_vals)\n\n# Print results\nstr_glue(\n  \"Black Defendants:\\n\",\n  \"  FPR: {round(b_fpr * 100, 1)}%\\n\",\n  \"  FNR: {round(b_fnr * 100, 1)}%\\n\",\n  \"  Accuracy: {round(b_acc * 100, 1)}%\\n\\n\"\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nBlack Defendants:\nFPR: 29.9%\nFNR: 32%\nAccuracy: 69%\n```\n\n\n:::\n\n```{.r .cell-code}\nstr_glue(\n  \"White Defendants:\\n\",\n  \"  FPR: {round(w_fpr * 100, 1)}%\\n\",\n  \"  FNR: {round(w_fnr * 100, 1)}%\\n\",\n  \"  Accuracy: {round(w_acc * 100, 1)}%\\n\"\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nWhite Defendants:\nFPR: 13.1%\nFNR: 57.1%\nAccuracy: 69.6%\n```\n\n\n:::\n:::\n\n\n\n\nAlthough our model has slightly better accuracy than COMPAS, it produces very similar results and shows the same level of disparities.\n\nPart of the reason models generate biased result is that they learns from historically biased data. We can't undo the historical patterns that shaped the data, and we often can't completely avoid using variables that carry implicit bias, especially when they carry predictive power. Recognizing this challenge is broadly referred to as **fairness-aware modeling**.\n\nBut there are still a range of strategies we can apply: understanding the data context, being critical about variables that may act as proxies for protected characteristics, and applying fairness techniques in the decision-making process to correct potential harm. We'll try to improve our logistic classification model using some of these ideas.\n\n# Adjust Classification Thresholds\n\nIn logistic regression, the model doesn't directly predict a \"yes\" or \"no\" outcome. It predicts a probability between 0 and 1 that an observation belongs to the positive class. A final classification decision still needs to be made. By default, the threshold is set at 0.5, meaning if the predicted probability is greater than 0.5, the case is classified as \"yes\", otherwise \"no\".\n\nBy adding `type = \"prob\"` in the `predict` function, we will get the results of **predicted probabilities** instead of class labels. This lets us adjust the decision threshold, which means, if we lower the decision threshold, the model is more likely to predict \"yes\".\n\nChanging the threshold affects how predictions fall into true or false positives and negatives, which in turn impacts error rates and fairness.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# This is the probability result\npred_probs <- predict(logit_model, newdata = test_data, type = \"prob\")\n\n# take a look at the predicted probabilities\npred_probs |> head(10)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          no       yes\n1  0.7724305 0.2275695\n2  0.2048619 0.7951381\n3  0.3381370 0.6618630\n4  0.6199372 0.3800628\n5  0.4953815 0.5046185\n6  0.7350560 0.2649440\n7  0.4632128 0.5367872\n8  0.5938938 0.4061062\n9  0.5493853 0.4506147\n10 0.5636980 0.4363020\n```\n\n\n:::\n:::\n\n\n\n\nNow let's try to set different classification thresholds for different groups!\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Attach pred_probs to the test data\ntest_pred <- \n  test_data |> \n  mutate(pred_prob = pred_probs$yes)\n\n# Define separate thresholds we want to use\nthresholds <- list(\n  African_American = 0.6,\n  Caucasian = 0.5\n)\n\n# Create a new \"predicted\" column based on group-specific thresholds.\n# For African-American and Caucasian individuals, apply separate thresholds.\n# For all others, use the default threshold of 0.5.\ntest_pred <- test_pred |>\n  mutate(predicted = case_when(\n    race == \"African-American\" & pred_prob > thresholds$African_American ~ \"yes\",\n    race == \"African-American\" & pred_prob <= thresholds$African_American ~ \"no\",\n    race == \"Caucasian\" & pred_prob > thresholds$Caucasian ~ \"yes\",\n    race == \"Caucasian\" & pred_prob <= thresholds$Caucasian ~ \"no\",\n    pred_prob > 0.5 ~ \"yes\",\n    TRUE ~ \"no\"\n  ))\n```\n:::\n\n\n\n\nNow that we have applied group-specific thresholds, we can calculate and compare performance metrics again: FPR, FNR and Accuracy, for African-American and Caucasian defendants, separately.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# three metrics, FNR, FPR and Accuracy for both race\nb_vals <- confusion_by_race(test_pred, \"African-American\")\nb_fpr <- b_vals[\"FP\"] / (b_vals[\"FP\"] + b_vals[\"TN\"])\nb_fnr <- b_vals[\"FN\"] / (b_vals[\"FN\"] + b_vals[\"TP\"])\nb_acc <- (b_vals[\"TP\"] + b_vals[\"TN\"]) / sum(b_vals)\n\nw_vals <- confusion_by_race(test_pred, \"Caucasian\")\nw_fpr <- w_vals[\"FP\"] / (w_vals[\"FP\"] + w_vals[\"TN\"])\nw_fnr <- w_vals[\"FN\"] / (w_vals[\"FN\"] + w_vals[\"TP\"])\nw_acc <- (w_vals[\"TP\"] + w_vals[\"TN\"]) / sum(w_vals)\n\n# Print results\nstr_glue(\n  \"Black Defendants:\\n\",\n  \"  FPR: {round(b_fpr * 100, 1)}%\\n\",\n  \"  FNR: {round(b_fnr * 100, 1)}%\\n\",\n  \"  Accuracy: {round(b_acc * 100, 1)}%\\n\\n\"\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nBlack Defendants:\nFPR: 12.4%\nFNR: 59.4%\nAccuracy: 63.3%\n```\n\n\n:::\n\n```{.r .cell-code}\nstr_glue(\n  \"White Defendants:\\n\",\n  \"  FPR: {round(w_fpr * 100, 1)}%\\n\",\n  \"  FNR: {round(w_fnr * 100, 1)}%\\n\",\n  \"  Accuracy: {round(w_acc * 100, 1)}%\\n\"\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nWhite Defendants:\nFPR: 13.1%\nFNR: 57.1%\nAccuracy: 69.6%\n```\n\n\n:::\n:::\n\n\n\n\nToday's analysis is built on [Chapter 7](https://urbanspatial.github.io/PublicPolicyAnalytics/people-based-ml-models-algorithmic-fairness.html) of [Public Policy Analysis](https://urbanspatial.github.io/PublicPolicyAnalytics/). In this chapter, the author introduced a few guildlines for **an \"equity threshold\"**,\n\n-   Minimize differences in False Positive Rates (FPR) and False Negative Rates (FNR) between racial groups, while keeping both rates relatively low.\n-   Minimize differences in Accuracy rates between racial groups, while keeping the overall Accuracy high.\n\nHow would you interpret our new results? Would you consider this a better and more equitable model, or maybe there is more room for improvement?\n\n# Lab Report\n\nYou've seen how changing the decision threshold affects fairness metrics. Previously, we tested one pair of thresholds (0.6 for Black defendants and 0.5 for White defendants). But that was just one possibility. Are there other threshold pairs that might lead to even better fairness or overall performance? How to find them?\n\nYour goal is to **explore multiple possible threshold combinations** to see whether some produce better fairness, better accuracy, or a better balance of both. There is no perfect solution: changing thresholds will always involve trade-offs. Your job is to think like a data scientist who has to explain these trade-offs to stakeholders.\n\n## **Your Task**\n\n1.  **Design your approach.** Decide what racial groups/performance metrics you want to focus on and which threshold values you want to try. For threshold values, you can:\n\n-   Pick several threshold pairs based on intuition, or\n\n-   Use a more systematic approach such as sensitivity analysis by testing a series of thresholds (e.g., 0.1 to 1.0) for both groups.\n\n    Your goal here is simply to propose an exploration strategy.\n\n2.  **Run your analysis.**\\\n    For each pair, apply your thresholds, calculate metrics such as FPR, FNR, or Accuracy for both racial groups. You can reuse any part of our code to do this more efficiently.\n\n3.  **Communicate your findings.**\\\n    Use either tables or visualizations to show how your metrics change. You can simply put together a table to compare metrics across threshold pairs. Or you can choose to use line plots, bar charts, or [heatmap](https://r-graph-gallery.com/79-levelplot-with-ggplot2.html).\n\n4.  **Reflect and recommend.**\\\n    **Choose** **a recommended threshold pair** **based on your analysis**. Please include a short write-up to explain what you recommend and why, any trade-offs involved and how you'd explain your results to a general audience.\n\nThere's no perfect answer. This is about exploring, reasoning, and practicing fairness-aware modeling in action.\n\nPlease include all your work in a **Quarto document** and submit your **Rendered HTML file** to Canvas by **9am, Wednesday, Nov 26**.\n",
    "supporting": [
      "lab10_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}